### ISSUE TITLE
VSPs forked off the network

### ISSUE THREAD

**Issue by xaur** [decred/dcrwebapi#138]
We have around 400 live tickets at risk of being missed.

Most are due to 4 legacy VSPs getting forked off the network on May 8 when the new consensus rules activated, so they got stuck at block [552447](https://explorer.dcrdata.org/block/552447).

| Legacy VSP                                                | Live\* |
|-----------------------------------------------------------|-------:|
| [stakepool.eu](https://stakepool.eu/)                     |    190 |
| [stakey.com](https://stakey.com/)                         |     79 |
| [stakepool.dcrstats.com](https://stakepool.dcrstats.com)  |     77 |
| [decredvoting.com](https://decredvoting.com/)\*\*         |     55 |
| [decred.yieldwallet.io](https://decred.yieldwallet.io)    |      1 |

\* Live tickets at block 552447 (May 8), these are expected to increasingly [become missed](https://docs.decred.org/proof-of-stake/overview/) as time goes by.
\*\* Last time dcrwebapi successfully crawled decredvoting.com on 2021-05-11, its [stats](https://decredvoting.com/api/v2/stats) endpoint says `404 page not found` and we cannot know its sync status.

[Missed rate](https://explorer.dcrdata.org/charts?chart=missed-votes&zoom=kjj4vlft-konkcx08) is already ramping up:

![miss-rate](https://user-images.githubusercontent.com/24484727/118208083-a0ec6980-b455-11eb-8064-11f75136ceb2.png)

Missed tickets damage reputation of individual VSPs and Decred as a brand.

@tpruvot @dema501 @dyrk @gsampathkumar please update your dcrd/dcrwallet ASAP to save as much tickets as possible.

@David00 please check if your VSP is allright.

**Comment by David00** [comment]
Hi team,I am fairly sure my VSP is good (DecredVoting) but I will double check on it tonight. I am running v1.6.2 on several nodes but was previously running a mixed dcrstakepool and vspd node, so it's probably just my nginx config not forwarding requests to the stats endpoint.Thanks,DavidOn May 13, 2021 6:43 PM, xaur ***@***.***> wrote:
We have around 400 live tickets at risk of being missed.
Most are due to 4 legacy VSPs getting forked off the network on May 8 when the new consensus rules activated, so they got stuck at block 552447.
Legacy VSPLive*stakepool.eu190stakey.com79stakepool.dcrstats.com77decredvoting.com**55decred.yieldwallet.io1
* Live tickets at block 552447 (May 8), these are expected to increasingly become missed as time goes by.
** Last time dcrwebapi successfully crawled decredvoting.com on 2021-05-11, its stats endpoint says 404 page not found and we cannot know its sync status.
Missed rate is already ramping up:

Missed tickets damage reputation of individual VSPs and Decred as a brand.
@tpruvot @dema501 @dyrk @gsampathkumar please update your dcrd/dcrwallet ASAP to save as much tickets as possible.
@David00 please check if your VSP is allright.

**Comment by dema501** [comment]
@David00 @xaur 
I have installed  dcrstakepool version 1.5.0 
it requires dad/wallet 1.5 
https://github.com/decred/dcrstakepool/blob/master/docs/release-note-1.5.0.md#recommended-upgrade-path

Would it work with 1.6.3 ?

**Comment by xaur** [comment]
@dema501 sorry can't help ther but  I heard you got the answers in chat. I think other operators are building from master - it got many commits since 1.5 release in Jan 2020.

https://stakey.com/api/v2/stats gives me 502 Bad Gateway right now.

**Comment by tpruvot** [comment]
stakepool.eu was upgraded today, was 38 missed tickets over the 4 days of the fork but 150 are still live right now

**Comment by dema501** [comment]
@xaur  yes I have a problems with upgrade
wallets are up and running and keeps voting 
but dcrstakepool and stakepoold  are NOT

looking for help in chat

**Comment by dema501** [comment]
@xaur  stakey.com should works now

**Comment by xaur** [comment]
Thank you both for upgrading!

The move to vspd was not 100% smooth but lets do what is possible given the resources (https://github.com/decred/vspd/issues/231).

**Comment by xaur** [comment]
Last time I could query the status of stakepool.dcrstats.com was May 14 and it still had height 552447. Since May 16 it says "ERROR 502: Bad Gateway". @dyrk I hope the wallets are voting regardless of the web frontend and API.

**Comment by xaur** [comment]
YieldWallet's legacy VSP has upgraded and its single lucky ticket didn't miss https://decred.yieldwallet.io/stats

**Comment by xaur** [comment]
This issue has been resolved for the most part so I'm closing it. Feel free to reopen if necessary.

Live ticket counts in the involved legacy VSPs (as of writing): stakepool.eu (11), stakey.com (2), decredvoting.com (5), decred.yieldwallet.io (0 - voted all and shut down). I could not reach the admin of stakepool.dcrstats.com .

Thanks everyone for responding and upgrading.
